name: Build FluentMarvelSdk

on:
  workflow_dispatch:

  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./src/FluentMarvelSdk/
    - name: Build
      run: dotnet build --no-restore ./src/FluentMarvelSdk/